services:
  h2-database:
    image: alpine:latest
    command:
      - sh
      - -c
      - |
        # JDKの準備
        apk update
        apk add --no-cache openjdk21
        rm -rf /var/cache/apk/*
        if [ -e h2-2023-09-17.zip ]; then
          echo "file exists"
        else
          # H2のダウンロード
          mkdir -p /opt
          wget https://github.com/h2database/h2database/releases/download/version-2.2.224/h2-2023-09-17.zip
          unzip h2-2023-09-17.zip
          mv h2 /opt
          mkdir -p /opt/h2/data
        fi
        # データベースファイルの作成
        if [ ! -e /opt/h2/data/testdb.mv.db ]; then
          echo "Creating database file"
          echo "CREATE TABLE IF NOT EXISTS test (id INT PRIMARY KEY, name VARCHAR(255));" > /opt/h2/init.sql
          java -cp /opt/h2/bin/h2-2.2.224.jar org.h2.tools.RunScript -url jdbc:h2:/opt/h2/data/testdb -script /opt/h2/init.sql -user sa
        fi
        # H2サーバの起動
        java -cp /opt/h2/bin/h2-2.2.224.jar org.h2.tools.Server -tcp -tcpAllowOthers -web -webAllowOthers -pg -pgAllowOthers -baseDir /opt/h2/data
    ports:
      - 9092:9092
      - 5435:5435
      - 8082:8082

# jdbc:h2:tcp://localhost//opt/h2/data/testdb